### ISSUE TITLE
Not static, leak free

### ISSUE THREAD

**Issue by consp1racy** [AzimoLabs/AndroidKeyboardWatcher#2]
Hello, I like where this is going. I hope these suggestions help you building a robust tool people can use:

**1)**

Ditch `ìnitWith` as it does nothing. Have a `public KeyboardWatcher(Activity activity)` constructor instead. The client activity will hold a reference to an instance. So you can have multiple activities using keyboard watcher at the same time. Activity will create an instance in `onCreate` and keep it.

**2)**

Use a more robust way to get the root view. `android.R.id.content` can change by calling `Activity.setContentView(...)`. `Activity.getWindow().getDecorView().getRootView()` will not. See http://stackoverflow.com/a/11553582/2444099. Store the reference right after you get the activity in constructor.

**3)**

Define `private final ViewTreeObserver.OnGlobalLayoutListener viewTreeObserverListener = new GlobalLayoutListener();` You can do this because `rootView` is resolved at the point of execution.

**4)**

Use weak references for `activity`, `rootView` and `onKeyboardToggleListener`. As soon as the activity is destroyed, you lose the references and prevent leaks.

**5)**

Rename `bindKeyboardWatcher` to `setListener`. Remove `unbindKeyboardWatcher` because `setListener(null)`.

**6)**

Consider having `addListener` and `removeListener` instead of `setListener`.

**Comment by frogermcs** [comment]
Thanks for your suggestions. We'll go through them and make sure to improve quality of our code

**Comment by ervinmartirosyan** [comment]
@consp1racy Thank you for your comment!
I have found issue in **3** point:
On keyboard shown

**Comment by consp1racy** [comment]
Ah, so the root view takes up the whole screen....

Ok, we can store `activity.getWindow().getDecorView().getRootView()` in the `rootView` variable. Then in the layout listener we can access `rootView.getChildAt(0)` to get the content view which should have its height adjusted as expected.

**Comment by ervinmartirosyan** [comment]
Please review my pull request https://github.com/AzimoLabs/AndroidKeyboardWatcher/pull/4

**Comment by frogermcs** [comment]
Merged, thanks for it! :)
