### ISSUE TITLE
Full screen Mode does not work.

### ISSUE THREAD

**Issue by MIkeeJY** [AzimoLabs/AndroidKeyboardWatcher#9]
Because fullscreen mode doesn't resize,How to solve this.. Anyone got it?

**Comment by MIkeeJY** [comment]
I had the same problem, My Activity had a ScrollView as root view and with translucent statusbar activated it didn't resize correctly when keyboard showed... and conseguently the screen didn't scrolled hiding the input views.

Solution: Moved everything (layout and activity logic) inside a new Fragment. Then changed the Activity to only include this Fragment. Now everything works as expected!

This is the layout of the activity:

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"

    android:id="@+id/contentView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true" />

**Comment by lala9662** [comment]
yeah...when i used FLAG_TRANSLUCENT_STATUS flag, the keyboardwatcher dose not work

so sad :(
